const { Drug } = require('../models');
const { escapeRegex } = require('../utils/helpers');
function normalize(value = '') { return String(value).normalize('NFKD').replace(/[\u064B-\u065F\u0670]/g, '').replace(/[إأآا]/g, 'ا').replace(/ى/g, 'ي').replace(/ؤ/g, 'و').replace(/ئ/g, 'ي').replace(/ة/g, 'ه').replace(/[^\p{L}\p{N}\s.+%-]/gu, ' ').replace(/\s+/g, ' ').trim().toLowerCase(); }
function compact(value = '') { return normalize(value).replace(/\b\d+(?:\.\d+)?\s*(?:mg|mcg|g|gm|ml|iu|%|مجم|ملجم|جم|مل)\b/gi, '').trim(); }
function levenshtein(a, b) { const x = compact(a), y = compact(b); if (!x || !y) return Math.max(x.length, y.length); const dp = Array.from({ length: x.length + 1 }, () => Array(y.length + 1).fill(0)); for (let i = 0; i <= x.length; i++) dp[i][0] = i; for (let j = 0; j <= y.length; j++) dp[0][j] = j; for (let i = 1; i <= x.length; i++) for (let j = 1; j <= y.length; j++) dp[i][j] = Math.min(dp[i-1][j]+1, dp[i][j-1]+1, dp[i-1][j-1] + (x[i-1] === y[j-1] ? 0 : 1)); return dp[x.length][y.length]; }
function similarity(a, b) { const x = compact(a), y = compact(b); if (!x || !y) return 0; if (x === y) return 1; if (x.includes(y) || y.includes(x)) return Math.min(0.95, Math.max(0.72, Math.min(x.length, y.length) / Math.max(x.length, y.length))); const xs = new Set(x.split(' ')), ys = new Set(y.split(' ')); const inter = [...xs].filter((t) => ys.has(t)).length; const union = new Set([...xs, ...ys]).size || 1; const token = inter / union; const edit = 1 - levenshtein(x, y) / Math.max(x.length, y.length, 1); return Math.max(token, edit * 0.9); }
function candidates(drug) { return [drug.genericName, ...(drug.brandNames || []), ...(drug.aliases || []), drug.searchText, `${drug.genericName} ${drug.strength}`].filter(Boolean); }
function serializeMatch(drug, score) { return { matchedDrugId: drug._id.toString(), matchedDrugName: drug.genericName, score: Number(score.toFixed(3)), drug: serializeDrug(drug) }; }
function serializeDrug(drug) { return { id: drug._id.toString(), generic_name: drug.genericName, brand_names: drug.brandNames || [], aliases: drug.aliases || [], category: drug.category, dosage_form: drug.dosageForm, strength: drug.strength, description: drug.description || '' }; }
async function findMatches(query, { limit = 10, threshold = 0.45 } = {}) { const q = normalize(query); if (!q) return []; const safe = escapeRegex(q.slice(0, 120)); const regex = new RegExp(safe, 'i'); let rows = []; try { rows = await Drug.find({ isActive: { $ne: false }, $text: { $search: q } }, { score: { $meta: 'textScore' } }).sort({ score: { $meta: 'textScore' } }).limit(limit * 5).lean(); } catch (_) { rows = []; } const regexRows = await Drug.find({ isActive: { $ne: false }, $or: [{ genericName: regex }, { brandNames: regex }, { aliases: regex }, { searchText: regex }] }).limit(limit * 5).lean(); const map = new Map(); [...rows, ...regexRows].forEach((d) => map.set(String(d._id), d)); if (map.size < limit) (await Drug.find({ isActive: { $ne: false } }).limit(500).lean()).forEach((d) => map.set(String(d._id), d)); return [...map.values()].map((d) => ({ drug: d, score: Math.max(...candidates(d).map((c) => similarity(q, c))) })).filter((x) => x.score >= threshold).sort((a, b) => b.score - a.score).slice(0, limit).map((x) => serializeMatch(x.drug, x.score)); }
module.exports = { normalize, similarity, findMatches, serializeDrug };
