import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { MapPin, Save, X } from 'lucide-react';
import { postJson } from '../lib/api';
import { statusTone } from '../lib/utils';
import { usePreferences } from '../context/PreferencesContext';
import { useToast } from '../context/ToastContext';

const initialForm = { name: '', address: '', phone: '', email: '', working_hours: '', status: 'active', rating: '4.5', latitude: '30.0444', longitude: '31.2357', google_maps_url: '' };

export default function AddPharmacyPage() {
  const { t } = usePreferences();
  const toast = useToast();
  const navigate = useNavigate();
  const [form, setForm] = useState(initialForm);
  const [errors, setErrors] = useState({});
  const [saving, setSaving] = useState(false);
  function update(field, value) { setForm((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: '' })); }
  function validate() { const next = {}; if (!form.name.trim()) next.name = t('forms.nameRequired'); if (!form.phone.trim()) next.phone = t('forms.phoneRequired'); if (!form.address.trim()) next.address = t('forms.addressRequired'); if (form.email && !/^[^@]+@[^@]+\.[^@]+$/.test(form.email)) next.email = t('forms.emailInvalid'); if (!Number.isFinite(Number(form.latitude)) || Number(form.latitude) < -90 || Number(form.latitude) > 90) next.latitude = t('forms.latitudeInvalid'); if (!Number.isFinite(Number(form.longitude)) || Number(form.longitude) < -180 || Number(form.longitude) > 180) next.longitude = t('forms.longitudeInvalid'); if (Number(form.rating) < 0 || Number(form.rating) > 5) next.rating = t('forms.ratingInvalid'); setErrors(next); return !Object.keys(next).length; }
  async function submit(event) { event.preventDefault(); if (!validate()) return; setSaving(true); try { await postJson('/pharmacies', { ...form, rating: Number(form.rating || 0), latitude: Number(form.latitude || 0), longitude: Number(form.longitude || 0) }); toast.success(t('toast.saved')); navigate('/pharmacies'); } catch (error) { toast.error(error.message || t('toast.failed')); } finally { setSaving(false); } }
  return <form className="grid gap-6 xl:grid-cols-[1fr_22rem]" onSubmit={submit}>
    <div className="space-y-6">
      <section className="card p-6"><h3 className="text-xl font-semibold text-primary">{t('common.basicInformation')}</h3><div className="mt-5 grid gap-5 md:grid-cols-2"><div><label className="label">{t('common.name')}</label><input className="input" value={form.name} onChange={(e) => update('name', e.target.value)} placeholder={t('forms.pharmacyNamePlaceholder')} />{errors.name ? <p className="mt-1 text-sm text-rose-600">{errors.name}</p> : null}</div><div><label className="label">{t('common.status')}</label><select className="input" value={form.status} onChange={(e) => update('status', e.target.value)}><option value="active">{t('common.active')}</option><option value="inactive">{t('common.inactive')}</option></select></div></div></section>
      <section className="card p-6"><h3 className="text-xl font-semibold text-primary">{t('common.contactInformation')}</h3><div className="mt-5 grid gap-5 md:grid-cols-2"><div><label className="label">{t('common.phone')}</label><input className="input" value={form.phone} onChange={(e) => update('phone', e.target.value)} placeholder={t('forms.phonePlaceholder')} />{errors.phone ? <p className="mt-1 text-sm text-rose-600">{errors.phone}</p> : null}</div><div><label className="label">{t('common.email')}</label><input className="input" value={form.email} onChange={(e) => update('email', e.target.value)} placeholder={t('forms.emailPlaceholder')} />{errors.email ? <p className="mt-1 text-sm text-rose-600">{errors.email}</p> : null}</div></div></section>
      <section className="card p-6"><h3 className="text-xl font-semibold text-primary">{t('common.location')}</h3><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><label className="label">{t('common.address')}</label><input className="input" value={form.address} onChange={(e) => update('address', e.target.value)} placeholder={t('forms.addressPlaceholder')} />{errors.address ? <p className="mt-1 text-sm text-rose-600">{errors.address}</p> : null}</div><div><label className="label">{t('common.latitude')}</label><input type="number" step="0.0001" className="input" value={form.latitude} onChange={(e) => update('latitude', e.target.value)} />{errors.latitude ? <p className="mt-1 text-sm text-rose-600">{errors.latitude}</p> : null}</div><div><label className="label">{t('common.longitude')}</label><input type="number" step="0.0001" className="input" value={form.longitude} onChange={(e) => update('longitude', e.target.value)} />{errors.longitude ? <p className="mt-1 text-sm text-rose-600">{errors.longitude}</p> : null}</div><div className="md:col-span-2"><label className="label">{t('common.googleMapsUrl')}</label><input className="input" value={form.google_maps_url} onChange={(e) => update('google_maps_url', e.target.value)} placeholder={t('forms.mapsPlaceholder')} /></div></div></section>
      <section className="card p-6"><h3 className="text-xl font-semibold text-primary">{t('common.operations')}</h3><div className="mt-5 grid gap-5 md:grid-cols-2"><div><label className="label">{t('common.workingHours')}</label><input className="input" value={form.working_hours} onChange={(e) => update('working_hours', e.target.value)} placeholder={t('forms.workingHoursPlaceholder')} /></div><div><label className="label">{t('common.rating')}</label><input type="number" min="0" max="5" step="0.1" className="input" value={form.rating} onChange={(e) => update('rating', e.target.value)} />{errors.rating ? <p className="mt-1 text-sm text-rose-600">{errors.rating}</p> : null}</div></div></section>
    </div>
    <aside className="card h-fit p-6 xl:sticky xl:top-6"><h3 className="text-xl font-semibold text-primary">{t('common.livePreview')}</h3><div className="mt-5 sub-card p-5"><p className="text-2xl font-semibold text-primary">{form.name || t('common.pharmacy')}</p><p className="mt-2 text-sm text-muted">{form.address || t('common.address')}</p><p className="mt-3 text-sm text-muted">{form.phone || t('common.phone')}</p><p className="mt-1 text-sm text-muted">{form.email || t('common.email')}</p><span className={`mt-4 badge ${statusTone(form.status)}`}>{t(`common.${form.status}`, form.status)}</span><p className="mt-4 text-sm text-muted">{t('common.rating')}: {form.rating}</p></div>{form.google_maps_url || (form.latitude && form.longitude) ? <a className="btn-secondary mt-4 w-full gap-2" target="_blank" rel="noreferrer" href={form.google_maps_url || `https://www.google.com/maps?q=${form.latitude},${form.longitude}`}><MapPin className="h-4 w-4" />{t('actions.openMaps')}</a> : null}<div className="mt-6 flex flex-col gap-3"><button type="submit" className="btn-primary gap-2" disabled={saving}><Save className="h-4 w-4" />{saving ? t('app.loading') : t('actions.save')}</button><button type="button" className="btn-secondary gap-2" onClick={() => navigate('/pharmacies')}><X className="h-4 w-4" />{t('actions.cancel')}</button></div></aside>
  </form>;
}
