import { useMemo, useState } from 'react';
import { CheckCircle2, Eye, XCircle } from 'lucide-react';
import ConfirmDialog from '../components/ConfirmDialog';
import { demoRequests } from '../lib/demoData';
import { formatDate, statusTone } from '../lib/utils';
import { usePreferences } from '../context/PreferencesContext';
import { useToast } from '../context/ToastContext';

export default function PharmacyRequestsPage() {
  const { t, language } = usePreferences(); const toast = useToast(); const [tab, setTab] = useState('pending'); const [rows, setRows] = useState(demoRequests); const [rejecting, setRejecting] = useState(null);
  const filtered = useMemo(() => rows.filter((item) => item.status === tab), [rows, tab]);
  function updateStatus(item, status) { setRows((current) => current.map((row) => row.id === item.id ? { ...row, status } : row)); toast.success(t('toast.updated')); }
  return <div className="space-y-6"><section className="card p-6"><div className="flex flex-wrap gap-2">{['pending','approved','rejected'].map((key) => <button key={key} className={tab === key ? 'btn-primary' : 'btn-secondary'} onClick={() => setTab(key)}>{t(`common.${key}`)}</button>)}</div></section><section className="grid gap-4 xl:grid-cols-2">{filtered.map((item) => <article key={item.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-semibold text-primary">{item.pharmacy_name}</h3><p className="mt-2 text-sm text-muted">{item.address}</p></div><span className={`badge ${statusTone(item.status)}`}>{t(`common.${item.status}`)}</span></div><div className="mt-4 grid gap-3 text-sm md:grid-cols-2"><p><span className="text-muted">{t('common.owner')}: </span><span className="font-medium text-primary">{item.owner_name}</span></p><p><span className="text-muted">{t('common.phone')}: </span><span className="font-medium text-primary">{item.phone}</span></p><p><span className="text-muted">{t('common.email')}: </span><span className="font-medium text-primary">{item.email}</span></p><p><span className="text-muted">{t('common.createdDate')}: </span><span className="font-medium text-primary">{formatDate(item.created_at, language)}</span></p></div><div className="mt-5 flex flex-wrap gap-2"><button className="btn-secondary gap-2"><Eye className="h-4 w-4" />{t('actions.review')}</button>{item.status === 'pending' ? <><button className="btn-primary gap-2" onClick={() => updateStatus(item, 'approved')}><CheckCircle2 className="h-4 w-4" />{t('actions.approve')}</button><button className="btn-danger gap-2" onClick={() => setRejecting(item)}><XCircle className="h-4 w-4" />{t('actions.reject')}</button></> : null}</div></article>)}</section><ConfirmDialog open={Boolean(rejecting)} title={t('actions.reject')} message={rejecting?.pharmacy_name} confirmText={t('actions.reject')} onClose={() => setRejecting(null)} onConfirm={() => { updateStatus(rejecting, 'rejected'); setRejecting(null); }} /></div>;
}
