import { useMemo, useState } from 'react';
import { CheckCircle2, Eye, UserPlus, XCircle } from 'lucide-react';
import Drawer from '../components/Drawer';
import { demoTickets } from '../lib/demoData';
import { formatDate, priorityTone, statusTone } from '../lib/utils';
import { usePreferences } from '../context/PreferencesContext';
import { useToast } from '../context/ToastContext';

export default function SupportTicketsPage() {
  const { t, language } = usePreferences(); const toast = useToast(); const [tab, setTab] = useState('open'); const [rows, setRows] = useState(demoTickets); const [selected, setSelected] = useState(null);
  const filtered = useMemo(() => rows.filter((item) => item.status === tab), [rows, tab]);
  function updateTicket(item, changes) { setRows((current) => current.map((row) => row.id === item.id ? { ...row, ...changes } : row)); toast.success(t('toast.updated')); }
  return <div className="space-y-6"><section className="card p-6"><div className="flex flex-wrap gap-2">{['open','in_progress','resolved','closed'].map((key) => <button key={key} className={tab === key ? 'btn-primary' : 'btn-secondary'} onClick={() => setTab(key)}>{t(key === 'in_progress' ? 'common.inProgress' : `common.${key}`)}</button>)}</div></section><section className="card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="table-head"><tr><th className="px-5 py-4 font-medium">{t('common.title')}</th><th className="px-5 py-4 font-medium">{t('common.user')}</th><th className="px-5 py-4 font-medium">{t('common.priority')}</th><th className="px-5 py-4 font-medium">{t('common.status')}</th><th className="px-5 py-4 font-medium">{t('common.date')}</th><th className="px-5 py-4 font-medium">{t('common.actions')}</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-b border-soft"><td className="px-5 py-4 font-medium text-primary">{item.title}</td><td className="px-5 py-4 text-muted">{item.user}</td><td className="px-5 py-4"><span className={`badge ${priorityTone(item.priority)}`}>{item.priority}</span></td><td className="px-5 py-4"><span className={`badge ${statusTone(item.status)}`}>{item.status}</span></td><td className="px-5 py-4 text-muted">{formatDate(item.created_at, language)}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-2"><button className="btn-secondary !px-3 !py-2" onClick={() => setSelected(item)}><Eye className="h-4 w-4" /></button><button className="btn-secondary !px-3 !py-2" onClick={() => updateTicket(item, { status: 'in_progress', assigned_admin: 'Me' })}><UserPlus className="h-4 w-4" /></button><button className="btn-primary !px-3 !py-2" onClick={() => updateTicket(item, { status: 'resolved' })}><CheckCircle2 className="h-4 w-4" /></button><button className="btn-danger !px-3 !py-2" onClick={() => updateTicket(item, { status: 'closed' })}><XCircle className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div></section><Drawer open={Boolean(selected)} title={selected?.title} onClose={() => setSelected(null)}>{selected ? <div className="space-y-3"><p className="text-muted">{selected.message}</p>{[[t('common.user'), selected.user], [t('common.pharmacy'), selected.pharmacy], [t('common.priority'), selected.priority], [t('common.status'), selected.status], [t('common.assignedAdmin'), selected.assigned_admin]].map(([label, value]) => <div className="flex justify-between border-b border-soft pb-3" key={label}><span className="text-sm text-muted">{label}</span><span className="font-medium text-primary">{value}</span></div>)}</div> : null}</Drawer></div>;
}
