import { useMemo, useState } from 'react';
import { Eye, ShieldCheck, ToggleLeft, ToggleRight } from 'lucide-react';
import Drawer from '../components/Drawer';
import { demoUsers } from '../lib/demoData';
import { formatDate, statusTone } from '../lib/utils';
import { usePreferences } from '../context/PreferencesContext';
import { useToast } from '../context/ToastContext';

export default function UsersPage() {
  const { t, language } = usePreferences(); const toast = useToast(); const [rows, setRows] = useState(demoUsers); const [q, setQ] = useState(''); const [role, setRole] = useState(''); const [status, setStatus] = useState(''); const [selected, setSelected] = useState(null);
  const filtered = useMemo(() => rows.filter((item) => { const text = `${item.name} ${item.email}`.toLowerCase(); if (q && !text.includes(q.toLowerCase())) return false; if (role && item.role !== role) return false; if (status && item.status !== status) return false; return true; }), [rows, q, role, status]);
  function toggleUser(user) { setRows((current) => current.map((item) => item.id === user.id ? { ...item, status: item.status === 'active' ? 'inactive' : 'active' } : item)); toast.success(t('toast.updated')); }
  return <div className="space-y-6"><section className="card p-6"><div className="grid gap-4 md:grid-cols-3"><input className="input" placeholder={t('actions.searchPlaceholder')} value={q} onChange={(e) => setQ(e.target.value)} /><select className="input" value={role} onChange={(e) => setRole(e.target.value)}><option value="">{t('common.role')}: {t('common.all')}</option>{['super_admin','pharmacy_admin','support_admin','user'].map((x) => <option key={x}>{x}</option>)}</select><select className="input" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">{t('common.status')}: {t('common.all')}</option><option value="active">{t('common.active')}</option><option value="inactive">{t('common.inactive')}</option></select></div></section><section className="card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="table-head"><tr><th className="px-5 py-4 font-medium">{t('common.name')}</th><th className="px-5 py-4 font-medium">{t('common.email')}</th><th className="px-5 py-4 font-medium">{t('common.role')}</th><th className="px-5 py-4 font-medium">{t('common.status')}</th><th className="px-5 py-4 font-medium">{t('common.assignedPharmacy')}</th><th className="px-5 py-4 font-medium">{t('common.lastLogin')}</th><th className="px-5 py-4 font-medium">{t('common.actions')}</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.id} className="border-b border-soft"><td className="px-5 py-4 font-medium text-primary">{user.name}</td><td className="px-5 py-4 text-muted">{user.email}</td><td className="px-5 py-4"><span className="badge border-cyan-200 bg-cyan-50 text-cyan-700 dark:border-cyan-400/30 dark:bg-cyan-500/10 dark:text-cyan-200">{user.role}</span></td><td className="px-5 py-4"><span className={`badge ${statusTone(user.status)}`}>{user.status}</span></td><td className="px-5 py-4 text-muted">{user.assigned_pharmacy}</td><td className="px-5 py-4 text-muted">{formatDate(user.last_login, language)}</td><td className="px-5 py-4"><div className="flex gap-2"><button className="btn-secondary !px-3 !py-2" onClick={() => setSelected(user)}><Eye className="h-4 w-4" /></button><button className="btn-secondary !px-3 !py-2" onClick={() => toast.info(t('actions.changeRole'))}><ShieldCheck className="h-4 w-4" /></button><button className="btn-secondary !px-3 !py-2" onClick={() => toggleUser(user)}>{user.status === 'active' ? <ToggleRight className="h-4 w-4" /> : <ToggleLeft className="h-4 w-4" />}</button></div></td></tr>)}</tbody></table></div></section><Drawer open={Boolean(selected)} title={selected?.name} onClose={() => setSelected(null)}>{selected ? <div className="space-y-3">{Object.entries(selected).map(([key, value]) => <div key={key} className="flex justify-between border-b border-soft pb-3"><span className="text-sm text-muted">{key}</span><span className="font-medium text-primary">{String(value)}</span></div>)}</div> : null}</Drawer></div>;
}
