module.exports = {
  User: require('./user.model'),
  Pharmacy: require('./pharmacy.model'),
  Drug: require('./drug.model'),
  InventorySnapshot: require('./inventory-snapshot.model'),
  Category: require('./category.model'),
  StoreCategory: require('./store-category.model'),
  StoreWarehouse: require('./store-warehouse.model'),
  StoreProduct: require('./store-product.model'),
  StorePerson: require('./store-person.model'),
  StoreInvoice: require('./store-invoice.model'),
  StoreReturn: require('./store-return.model'),
  StoreTransfer: require('./store-transfer.model'),
  StoreInventoryCount: require('./store-inventory-count.model'),
  StoreTreasuryMovement: require('./store-treasury-movement.model'),
  StoreSequence: require('./store-sequence.model'),
  AiLog: require('./ai-log.model'),
  SystemLog: require('./system-log.model'),
  Notification: require('./notification.model'),
  SupportTicket: require('./support-ticket.model'),
  OtpRequest: require('./otp-request.model'),
  Session: require('./session.model'),
  MfaChallenge: require('./mfa-challenge.model')
};
